{% set name = "lenapy" %}
{% set version = "1.0.2" %}
{% set python_min = "3.11" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/CNES/lenapy/archive/refs/tags/V{{ version }}.tar.gz
  sha256: d4f37024ede4a03f96c57882b3a56222e76ebeb119c65062c9bcf1c2756fdac5


build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}.*
    - packaging
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.6
    - xarray >=2024.2
    - gsw >=3.6.16
    - netCDF4 >=1.6.5
    - pyyaml >=6.0
    - dask >=2023.6
    - xesmf >=0.8.2
    - scipy >=1.15.2

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - lenapy
  commands:
    - pip check

about:
  home: "https://github.com/CNES/lenapy"
  license: AGPL-3.0-only
  license_file: LICENSE
  summary: "Lenapy is a Python library built around xarray, designed to facilitate the analysis of oceanographic and geophysical data"
  doc_url: https://lenapy.readthedocs.io/en/stable/
  dev_url: https://github.com/CNES/lenapy

extra:
  recipe-maintainers:
    - sfourest
    - hulecom
    - ArthurVincentCS
